/*
Copyright 2026.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

package v1

import (
	"google.golang.org/protobuf/proto"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
	"k8s.io/apimachinery/pkg/runtime/schema"

	protos "github.com/nvidia/nvsentinel/data-models/pkg/protos"
)

// MaintenanceRequest lives in the nvsentinel.dgxc.nvidia.com API group, not the
// nvsentinel.nvidia.com group used by ValidationRequest, so lifecycle-manager
// serves two groups. MR shares a group with ExternalRemediationRequest because
// the two form the bilateral node-handoff API (ADR-040, ADR-051).
//
// The version is "v1" to match the CRD generated by protoc-gen-crd, which
// hardcodes "v1" in its plugin source and does not currently expose a way to
// configure the version per CRD. Despite the v1 version string, the MR API is
// still pre-stable; ADR-051 governs its lifecycle.
const (
	// MaintenanceRequestAPIGroup is the API group MaintenanceRequest belongs to.
	MaintenanceRequestAPIGroup = "nvsentinel.dgxc.nvidia.com"
	// MaintenanceRequestVersion is the served and stored API version.
	MaintenanceRequestVersion = "v1"
	// MaintenanceRequestKind is the CRD kind.
	MaintenanceRequestKind = "MaintenanceRequest"
)

// GroupVersion is the GroupVersion used by MaintenanceRequest. It is
// distinct from SchemeGroupVersion (nvsentinel.nvidia.com/v1alpha1), which
// ValidationRequest uses.
var GroupVersion = schema.GroupVersion{
	Group:   MaintenanceRequestAPIGroup,
	Version: MaintenanceRequestVersion,
}

// SchemeBuilder is the SchemeBuilder for the
// nvsentinel.dgxc.nvidia.com API group. It is independent of SchemeBuilder in
// groupversion_info.go so the two groups can be registered separately — callers
// register both with the controller-runtime scheme.
var SchemeBuilder = runtime.NewSchemeBuilder(addKnownTypes)

// AddToScheme adds the nvsentinel.dgxc.nvidia.com/v1 types to the
// given scheme. Called from the lifecycle-manager binary's scheme setup, in
// addition to AddToScheme for the nvsentinel.nvidia.com group.
var AddToScheme = SchemeBuilder.AddToScheme

func addKnownTypes(scheme *runtime.Scheme) error {
	scheme.AddKnownTypes(
		GroupVersion,
		&MaintenanceRequest{},
		&MaintenanceRequestList{},
	)
	metav1.AddToGroupVersion(scheme, GroupVersion)

	return nil
}

// MaintenanceRequest is the Kubernetes API wrapper for the proto-generated
// MaintenanceRequestSpec/Status types.
//
// Per ADR-051, the CRD schema is generated from proto (via protoc-gen-crd) and
// the Spec/Status field shapes are owned entirely by the .proto file. This
// wrapper exists ONLY to provide the Kubernetes machinery (TypeMeta,
// ObjectMeta, runtime.Object interface) that the proto-generated types do not
// supply on their own — it deliberately defines no fields of its own beyond
// what Kubernetes requires.
//
// The CRD lives at
// distros/kubernetes/nvsentinel/charts/lifecycle-manager/crds/maintenance_request.crd.yaml
// and is generated from data-models/protobufs/maintenance_request.proto.
//
// DeepCopy is hand-written below because Spec and Status are proto messages;
// the package-level +kubebuilder:object:generate=true marker in
// groupversion_info.go would otherwise have controller-gen emit conflicting
// implementations that cannot correctly copy a proto message.
//
// +kubebuilder:object:generate=false
type MaintenanceRequest struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`

	// Spec and Status are pointer fields because the underlying proto types
	// embed protoimpl.MessageState (which contains a sync.Mutex). Copying a
	// proto message by value would trip go vet's copylocks analyzer. Pointer
	// fields also match the CRD schema's `nullable: true` for spec and status
	// produced by protoc-gen-crd.
	Spec   *protos.MaintenanceRequestSpec   `json:"spec,omitempty"`
	Status *protos.MaintenanceRequestStatus `json:"status,omitempty"`
}

// MaintenanceRequestList is the list wrapper, required by the runtime.Object
// interface for list operations.
//
// +kubebuilder:object:generate=false
type MaintenanceRequestList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []MaintenanceRequest `json:"items"`
}

// DeepCopyObject implements runtime.Object.
func (m *MaintenanceRequest) DeepCopyObject() runtime.Object {
	if m == nil {
		return nil
	}

	out := new(MaintenanceRequest)
	m.DeepCopyInto(out)

	return out
}

// DeepCopy returns a deep copy of the receiver.
func (m *MaintenanceRequest) DeepCopy() *MaintenanceRequest {
	if m == nil {
		return nil
	}

	return m.DeepCopyObject().(*MaintenanceRequest)
}

// DeepCopyInto copies the receiver into out.
//
// Spec and Status are proto messages and use proto.Clone for deep-copy, which
// is the canonical way to deep-copy a protobuf message. nil pointer inputs
// produce nil pointer outputs. proto.Clone returns proto.Message but the
// runtime type is always the same concrete type as the input; a failed
// assertion would indicate proto runtime corruption, and panicking is the right
// response because controller-runtime recovers and re-queues.
func (m *MaintenanceRequest) DeepCopyInto(out *MaintenanceRequest) {
	out.TypeMeta = m.TypeMeta
	m.ObjectMeta.DeepCopyInto(&out.ObjectMeta)

	if m.Spec != nil {
		out.Spec = proto.Clone(m.Spec).(*protos.MaintenanceRequestSpec)
	}

	if m.Status != nil {
		out.Status = proto.Clone(m.Status).(*protos.MaintenanceRequestStatus)
	}
}

// DeepCopyObject implements runtime.Object.
func (l *MaintenanceRequestList) DeepCopyObject() runtime.Object {
	if l == nil {
		return nil
	}

	out := new(MaintenanceRequestList)
	l.DeepCopyInto(out)

	return out
}

// DeepCopy returns a deep copy of the receiver.
func (l *MaintenanceRequestList) DeepCopy() *MaintenanceRequestList {
	if l == nil {
		return nil
	}

	return l.DeepCopyObject().(*MaintenanceRequestList)
}

// DeepCopyInto copies the receiver into out.
func (l *MaintenanceRequestList) DeepCopyInto(out *MaintenanceRequestList) {
	out.TypeMeta = l.TypeMeta
	l.ListMeta.DeepCopyInto(&out.ListMeta)

	if l.Items != nil {
		out.Items = make([]MaintenanceRequest, len(l.Items))
		for i := range l.Items {
			l.Items[i].DeepCopyInto(&out.Items[i])
		}
	}
}
