/*
Copyright 2026.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

package v1

import (
	"bytes"
	"encoding/json"
	"fmt"

	"google.golang.org/protobuf/encoding/protojson"
	"google.golang.org/protobuf/proto"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"

	protos "github.com/nvidia/nvsentinel/data-models/pkg/protos"
)

// The MaintenanceRequest wrapper embeds proto-generated types in its Spec and
// Status fields. Several of those types use google.protobuf well-known types —
// most prominently google.protobuf.Timestamp on Condition and on
// spec.startTime — that have a canonical JSON encoding defined by the protobuf
// JSON spec (RFC3339 strings for Timestamp) and emitted by
// google.golang.org/protobuf/encoding/protojson.
//
// The CRD schema generated by protoc-gen-crd matches that canonical encoding
// (startTime: type=string, format=RFC3339). However, the standard encoding/json
// package — which controller-runtime's client and the Kubernetes apimachinery
// serializer ultimately invoke — does NOT know about proto well-known types and
// falls back to reflecting over the Go struct, producing
// `{"seconds": N, "nanos": M}` for Timestamp. That object form fails CRD
// validation with HTTP 422.
//
// The fix is to override MarshalJSON/UnmarshalJSON on the wrapper so that
// TypeMeta and ObjectMeta flow through encoding/json as usual, but Spec and
// Status are routed through protojson. This keeps proto as the source of truth
// for the schema (per ADR-051) without introducing a separate hand-mirrored Go
// shape.
//
// Future spec fields that use other well-known proto types
// (google.protobuf.Duration, etc.) get the correct behavior for free, since
// protojson handles them all canonically.

// protojsonUnmarshalOpts is the lenient unmarshal config used for k8s-side
// reads. DiscardUnknown=true matches apimachinery's behavior of tolerating
// server-side schema additions; everything else is the protojson default.
var protojsonUnmarshalOpts = protojson.UnmarshalOptions{DiscardUnknown: true}

// jsonEnvelope mirrors the wire shape of the wrapper but pre-encodes Spec and
// Status as opaque JSON blobs so they can be produced by protojson (marshal) or
// fed to protojson (unmarshal). TypeMeta and ObjectMeta are standard k8s types
// handled by encoding/json.
type jsonEnvelope struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	Spec              json.RawMessage `json:"spec,omitempty"`
	Status            json.RawMessage `json:"status,omitempty"`
}

// MarshalJSON serialises a MaintenanceRequest with TypeMeta and ObjectMeta via
// encoding/json and Spec / Status via protojson. This ensures proto well-known
// types (Timestamp, etc.) emit their canonical JSON forms rather than the
// {seconds, nanos} reflection-default form, matching the CRD's OpenAPI schema.
func (m *MaintenanceRequest) MarshalJSON() ([]byte, error) {
	out := jsonEnvelope{
		TypeMeta:   m.TypeMeta,
		ObjectMeta: m.ObjectMeta,
	}

	if m.Spec != nil {
		b, err := protojson.Marshal(m.Spec)
		if err != nil {
			return nil, fmt.Errorf("marshal MaintenanceRequest.spec via protojson: %w", err)
		}

		out.Spec = b
	}

	if m.Status != nil {
		b, err := protojson.Marshal(m.Status)
		if err != nil {
			return nil, fmt.Errorf("marshal MaintenanceRequest.status via protojson: %w", err)
		}

		out.Status = b
	}

	return json.Marshal(&out)
}

// UnmarshalJSON deserialises a MaintenanceRequest with the inverse of
// MarshalJSON: TypeMeta and ObjectMeta via encoding/json, Spec / Status via
// protojson with DiscardUnknown enabled so that forward-compat field additions
// on the server side don't break older clients.
func (m *MaintenanceRequest) UnmarshalJSON(data []byte) error {
	var in jsonEnvelope
	if err := json.Unmarshal(data, &in); err != nil {
		return fmt.Errorf("unmarshal MaintenanceRequest envelope: %w", err)
	}

	m.TypeMeta = in.TypeMeta
	m.ObjectMeta = in.ObjectMeta

	if isJSONPresent(in.Spec) {
		spec := &protos.MaintenanceRequestSpec{}
		if err := protojsonUnmarshalOpts.Unmarshal(in.Spec, spec); err != nil {
			return fmt.Errorf("unmarshal MaintenanceRequest.spec via protojson: %w", err)
		}

		m.Spec = spec
	} else {
		m.Spec = nil
	}

	if isJSONPresent(in.Status) {
		status := &protos.MaintenanceRequestStatus{}
		if err := protojsonUnmarshalOpts.Unmarshal(in.Status, status); err != nil {
			return fmt.Errorf("unmarshal MaintenanceRequest.status via protojson: %w", err)
		}

		m.Status = status
	} else {
		m.Status = nil
	}

	return nil
}

// listJSONEnvelope mirrors the wire shape of MaintenanceRequestList. Items are
// deserialised via the per-item UnmarshalJSON above.
type listJSONEnvelope struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []MaintenanceRequest `json:"items"`
}

// MarshalJSON delegates each item to MaintenanceRequest.MarshalJSON, which in
// turn applies protojson to Spec / Status. ListMeta uses encoding/json as it is
// a standard k8s type.
func (l *MaintenanceRequestList) MarshalJSON() ([]byte, error) {
	return json.Marshal(&listJSONEnvelope{
		TypeMeta: l.TypeMeta,
		ListMeta: l.ListMeta,
		Items:    l.Items,
	})
}

// UnmarshalJSON deserialises the envelope and delegates each item to
// MaintenanceRequest.UnmarshalJSON.
func (l *MaintenanceRequestList) UnmarshalJSON(data []byte) error {
	var in listJSONEnvelope
	if err := json.Unmarshal(data, &in); err != nil {
		return fmt.Errorf("unmarshal MaintenanceRequestList: %w", err)
	}

	l.TypeMeta = in.TypeMeta
	l.ListMeta = in.ListMeta
	l.Items = in.Items

	return nil
}

// isJSONPresent reports whether the given RawMessage carries a real JSON
// payload, treating empty, missing, or explicit `null` as absence.
func isJSONPresent(raw json.RawMessage) bool {
	if len(raw) == 0 {
		return false
	}

	return !bytes.Equal(bytes.TrimSpace(raw), []byte("null"))
}

// Compile-time check that the proto types implement proto.Message — guards
// against the protos package changing the type shape in an incompatible way.
var (
	_ proto.Message = (*protos.MaintenanceRequestSpec)(nil)
	_ proto.Message = (*protos.MaintenanceRequestStatus)(nil)
)
