// Copyright (c) 2025, NVIDIA CORPORATION.  All rights reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        v6.33.0
// source: external_remediation.proto

package protos

import (
	_ "github.com/yandex/protoc-gen-crd/library/go/k8s/protoc_gen_crd/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Condition is the wire equivalent of metav1.Condition. The janitor/pkg/condition
// adapter package converts between this proto representation and metav1.Condition
// at the controller boundary so existing controller-runtime helpers
// (meta.SetStatusCondition, meta.IsStatusConditionTrue) continue to work.
type Condition struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// type is the condition type (e.g. "NVSentinelOwnershipReleased",
	// "ExternalRemediationComplete").
	Type string `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	// status is one of "True", "False", "Unknown".
	Status string `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	// observedGeneration is the .metadata.generation that the condition was set
	// based upon.
	ObservedGeneration int64 `protobuf:"varint,3,opt,name=observedGeneration,proto3" json:"observedGeneration,omitempty"`
	// lastTransitionTime is the last time the condition transitioned from one
	// status to another.
	LastTransitionTime *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=lastTransitionTime,proto3" json:"lastTransitionTime,omitempty"`
	// reason contains a programmatic identifier indicating the reason for the
	// condition's last transition (e.g. "ReleaseTaintApplied",
	// "AwaitingExternalSystem", "ReleaseTaintFailed").
	Reason string `protobuf:"bytes,5,opt,name=reason,proto3" json:"reason,omitempty"`
	// message is a human-readable message indicating details about the
	// transition.
	Message string `protobuf:"bytes,6,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *Condition) Reset() {
	*x = Condition{}
	if protoimpl.UnsafeEnabled {
		mi := &file_external_remediation_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Condition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Condition) ProtoMessage() {}

func (x *Condition) ProtoReflect() protoreflect.Message {
	mi := &file_external_remediation_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Condition.ProtoReflect.Descriptor instead.
func (*Condition) Descriptor() ([]byte, []int) {
	return file_external_remediation_proto_rawDescGZIP(), []int{0}
}

func (x *Condition) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Condition) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Condition) GetObservedGeneration() int64 {
	if x != nil {
		return x.ObservedGeneration
	}
	return 0
}

func (x *Condition) GetLastTransitionTime() *timestamppb.Timestamp {
	if x != nil {
		return x.LastTransitionTime
	}
	return nil
}

func (x *Condition) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *Condition) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// ExternalRemediationRequestSpec is the desired state of an ERR. The
// HealthEvent describes the fault that produced the ERR. The wrapper struct
// leaves room for future ERR-specific spec fields (priority, expected duration,
// external-system hints) without requiring changes to the HealthEvent proto.
type ExternalRemediationRequestSpec struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// healthEvent is a full copy of the triaged HealthEvent that produced this
	// ERR. Reuses the existing HealthEvent message by reference; adding a field
	// to HealthEvent propagates here automatically.
	HealthEvent *HealthEvent `protobuf:"bytes,1,opt,name=healthEvent,proto3" json:"healthEvent,omitempty"`
}

func (x *ExternalRemediationRequestSpec) Reset() {
	*x = ExternalRemediationRequestSpec{}
	if protoimpl.UnsafeEnabled {
		mi := &file_external_remediation_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ExternalRemediationRequestSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExternalRemediationRequestSpec) ProtoMessage() {}

func (x *ExternalRemediationRequestSpec) ProtoReflect() protoreflect.Message {
	mi := &file_external_remediation_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExternalRemediationRequestSpec.ProtoReflect.Descriptor instead.
func (*ExternalRemediationRequestSpec) Descriptor() ([]byte, []int) {
	return file_external_remediation_proto_rawDescGZIP(), []int{1}
}

func (x *ExternalRemediationRequestSpec) GetHealthEvent() *HealthEvent {
	if x != nil {
		return x.HealthEvent
	}
	return nil
}

// ExternalRemediationRequestStatus is the observed state of an ERR. Status
// transitions are driven by the ERR reconciler (NVSentinelOwnershipReleased)
// and the external system (ExternalRemediationComplete) — see ADR-040 for the
// condition state machine.
type ExternalRemediationRequestStatus struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// conditions represent the latest available observations of the ERR's
	// current state. See ADR-040 for the canonical type names and reasons.
	Conditions []*Condition `protobuf:"bytes,1,rep,name=conditions,proto3" json:"conditions,omitempty"`
}

func (x *ExternalRemediationRequestStatus) Reset() {
	*x = ExternalRemediationRequestStatus{}
	if protoimpl.UnsafeEnabled {
		mi := &file_external_remediation_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ExternalRemediationRequestStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExternalRemediationRequestStatus) ProtoMessage() {}

func (x *ExternalRemediationRequestStatus) ProtoReflect() protoreflect.Message {
	mi := &file_external_remediation_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExternalRemediationRequestStatus.ProtoReflect.Descriptor instead.
func (*ExternalRemediationRequestStatus) Descriptor() ([]byte, []int) {
	return file_external_remediation_proto_rawDescGZIP(), []int{2}
}

func (x *ExternalRemediationRequestStatus) GetConditions() []*Condition {
	if x != nil {
		return x.Conditions
	}
	return nil
}

// ExternalRemediationRequest is the exit door from NVSentinel ownership.
// Created by fault-remediation when triage maps a fault to the CUSTOM
// recommended action (per ADR-036) with a customRecommendedAction configured
// to produce an ERR.
//
// See ADR-040 (docs/designs/040-external-remediation-request.md) for the full
// design including the asymmetric ExternalRemediationComplete=True vs False
// handling, the cleanup finalizer, the release taint, and the
// nvsentinel.dgxc.nvidia.com/managed label coordination mechanism.
type ExternalRemediationRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Spec   *ExternalRemediationRequestSpec   `protobuf:"bytes,1,opt,name=spec,proto3" json:"spec,omitempty"`
	Status *ExternalRemediationRequestStatus `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
}

func (x *ExternalRemediationRequest) Reset() {
	*x = ExternalRemediationRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_external_remediation_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ExternalRemediationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExternalRemediationRequest) ProtoMessage() {}

func (x *ExternalRemediationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_external_remediation_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExternalRemediationRequest.ProtoReflect.Descriptor instead.
func (*ExternalRemediationRequest) Descriptor() ([]byte, []int) {
	return file_external_remediation_proto_rawDescGZIP(), []int{3}
}

func (x *ExternalRemediationRequest) GetSpec() *ExternalRemediationRequestSpec {
	if x != nil {
		return x.Spec
	}
	return nil
}

func (x *ExternalRemediationRequest) GetStatus() *ExternalRemediationRequestStatus {
	if x != nil {
		return x.Status
	}
	return nil
}

var File_external_remediation_proto protoreflect.FileDescriptor

var file_external_remediation_proto_rawDesc = []byte{
	0x0a, 0x1a, 0x65, 0x78, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x5f, 0x72, 0x65, 0x6d, 0x65, 0x64,
	0x69, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0a, 0x64, 0x61,
	0x74, 0x61, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65,
	0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74,
	0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x12, 0x68, 0x65, 0x61, 0x6c, 0x74,
	0x68, 0x5f, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x4e, 0x67,
	0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x79, 0x61, 0x6e, 0x64, 0x65, 0x78,
	0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x2d, 0x67, 0x65, 0x6e, 0x2d, 0x63, 0x72, 0x64, 0x2f,
	0x6c, 0x69, 0x62, 0x72, 0x61, 0x72, 0x79, 0x2f, 0x67, 0x6f, 0x2f, 0x6b, 0x38, 0x73, 0x2f, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x63, 0x5f, 0x67, 0x65, 0x6e, 0x5f, 0x63, 0x72, 0x64, 0x2f, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2f, 0x63, 0x72, 0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xe5, 0x01,
	0x0a, 0x09, 0x43, 0x6f, 0x6e, 0x64, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x12, 0x0a, 0x04, 0x74,
	0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12,
	0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x2e, 0x0a, 0x12, 0x6f, 0x62, 0x73, 0x65, 0x72,
	0x76, 0x65, 0x64, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x12, 0x6f, 0x62, 0x73, 0x65, 0x72, 0x76, 0x65, 0x64, 0x47, 0x65, 0x6e,
	0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x4a, 0x0a, 0x12, 0x6c, 0x61, 0x73, 0x74, 0x54,
	0x72, 0x61, 0x6e, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52,
	0x12, 0x6c, 0x61, 0x73, 0x74, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x54,
	0x69, 0x6d, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x18, 0x05, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x06, 0x72, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x12, 0x18, 0x0a, 0x07, 0x6d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x5b, 0x0a, 0x1e, 0x45, 0x78, 0x74, 0x65, 0x72, 0x6e, 0x61,
	0x6c, 0x52, 0x65, 0x6d, 0x65, 0x64, 0x69, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x53, 0x70, 0x65, 0x63, 0x12, 0x39, 0x0a, 0x0b, 0x68, 0x65, 0x61, 0x6c, 0x74,
	0x68, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x64,
	0x61, 0x74, 0x61, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x2e, 0x48, 0x65, 0x61, 0x6c, 0x74, 0x68,
	0x45, 0x76, 0x65, 0x6e, 0x74, 0x52, 0x0b, 0x68, 0x65, 0x61, 0x6c, 0x74, 0x68, 0x45, 0x76, 0x65,
	0x6e, 0x74, 0x22, 0x59, 0x0a, 0x20, 0x45, 0x78, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x52, 0x65,
	0x6d, 0x65, 0x64, 0x69, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x35, 0x0a, 0x0a, 0x63, 0x6f, 0x6e, 0x64, 0x69, 0x74,
	0x69, 0x6f, 0x6e, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x64, 0x61, 0x74,
	0x61, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x2e, 0x43, 0x6f, 0x6e, 0x64, 0x69, 0x74, 0x69, 0x6f,
	0x6e, 0x52, 0x0a, 0x63, 0x6f, 0x6e, 0x64, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x22, 0xa8, 0x02,
	0x0a, 0x1a, 0x45, 0x78, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x52, 0x65, 0x6d, 0x65, 0x64, 0x69,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x3e, 0x0a, 0x04,
	0x73, 0x70, 0x65, 0x63, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x2a, 0x2e, 0x64, 0x61, 0x74,
	0x61, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x2e, 0x45, 0x78, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c,
	0x52, 0x65, 0x6d, 0x65, 0x64, 0x69, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x53, 0x70, 0x65, 0x63, 0x52, 0x04, 0x73, 0x70, 0x65, 0x63, 0x12, 0x44, 0x0a, 0x06,
	0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x2c, 0x2e, 0x64,
	0x61, 0x74, 0x61, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x2e, 0x45, 0x78, 0x74, 0x65, 0x72, 0x6e,
	0x61, 0x6c, 0x52, 0x65, 0x6d, 0x65, 0x64, 0x69, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x3a, 0x83, 0x01, 0xaa, 0xa8, 0xfd, 0x97, 0x02, 0x7d, 0x0a, 0x15, 0x6e, 0x76, 0x73,
	0x65, 0x6e, 0x74, 0x69, 0x6e, 0x65, 0x6c, 0x2e, 0x6e, 0x76, 0x69, 0x64, 0x69, 0x61, 0x2e, 0x63,
	0x6f, 0x6d, 0x12, 0x1a, 0x45, 0x78, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x52, 0x65, 0x6d, 0x65,
	0x64, 0x69, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1a,
	0x65, 0x78, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x72, 0x65, 0x6d, 0x65, 0x64, 0x69, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x1b, 0x65, 0x78, 0x74, 0x65,
	0x72, 0x6e, 0x61, 0x6c, 0x72, 0x65, 0x6d, 0x65, 0x64, 0x69, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x72,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x73, 0x2a, 0x03, 0x65, 0x72, 0x72, 0x32, 0x0a, 0x6e, 0x76,
	0x73, 0x65, 0x6e, 0x74, 0x69, 0x6e, 0x65, 0x6c, 0x42, 0x35, 0x5a, 0x33, 0x67, 0x69, 0x74, 0x68,
	0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6e, 0x76, 0x69, 0x64, 0x69, 0x61, 0x2f, 0x6e, 0x76,
	0x73, 0x65, 0x6e, 0x74, 0x69, 0x6e, 0x65, 0x6c, 0x2f, 0x64, 0x61, 0x74, 0x61, 0x2d, 0x6d, 0x6f,
	0x64, 0x65, 0x6c, 0x73, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_external_remediation_proto_rawDescOnce sync.Once
	file_external_remediation_proto_rawDescData = file_external_remediation_proto_rawDesc
)

func file_external_remediation_proto_rawDescGZIP() []byte {
	file_external_remediation_proto_rawDescOnce.Do(func() {
		file_external_remediation_proto_rawDescData = protoimpl.X.CompressGZIP(file_external_remediation_proto_rawDescData)
	})
	return file_external_remediation_proto_rawDescData
}

var file_external_remediation_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_external_remediation_proto_goTypes = []interface{}{
	(*Condition)(nil),                        // 0: datamodels.Condition
	(*ExternalRemediationRequestSpec)(nil),   // 1: datamodels.ExternalRemediationRequestSpec
	(*ExternalRemediationRequestStatus)(nil), // 2: datamodels.ExternalRemediationRequestStatus
	(*ExternalRemediationRequest)(nil),       // 3: datamodels.ExternalRemediationRequest
	(*timestamppb.Timestamp)(nil),            // 4: google.protobuf.Timestamp
	(*HealthEvent)(nil),                      // 5: datamodels.HealthEvent
}
var file_external_remediation_proto_depIdxs = []int32{
	4, // 0: datamodels.Condition.lastTransitionTime:type_name -> google.protobuf.Timestamp
	5, // 1: datamodels.ExternalRemediationRequestSpec.healthEvent:type_name -> datamodels.HealthEvent
	0, // 2: datamodels.ExternalRemediationRequestStatus.conditions:type_name -> datamodels.Condition
	1, // 3: datamodels.ExternalRemediationRequest.spec:type_name -> datamodels.ExternalRemediationRequestSpec
	2, // 4: datamodels.ExternalRemediationRequest.status:type_name -> datamodels.ExternalRemediationRequestStatus
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_external_remediation_proto_init() }
func file_external_remediation_proto_init() {
	if File_external_remediation_proto != nil {
		return
	}
	file_health_event_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_external_remediation_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Condition); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_external_remediation_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ExternalRemediationRequestSpec); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_external_remediation_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ExternalRemediationRequestStatus); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_external_remediation_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ExternalRemediationRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_external_remediation_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_external_remediation_proto_goTypes,
		DependencyIndexes: file_external_remediation_proto_depIdxs,
		MessageInfos:      file_external_remediation_proto_msgTypes,
	}.Build()
	File_external_remediation_proto = out.File
	file_external_remediation_proto_rawDesc = nil
	file_external_remediation_proto_goTypes = nil
	file_external_remediation_proto_depIdxs = nil
}
